require 'json'
require 'forwardable'

require 'savon-multipart'
require_relative 'secret'

require_relative 'lib/cdx/client'
require_relative 'lib/cdx/logged_request'
require_relative 'lib/cdx/handle_error'
require_relative 'lib/cdx/user'
require_relative 'lib/cdx/system'
require_relative 'lib/cdx/activity'
require_relative 'lib/cdx/question'
require_relative 'lib/cdx/authenticator'
require_relative 'lib/cdx/answer'
require_relative 'lib/cdx/sign'
require_relative 'lib/cdx/manifest'
