module StatesHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def canadian_provinces
    [
      ['Ontario', 'ON'],
      ['Quebec', 'QC'],
      ['Nova Scotia', 'NS'],
      ['New Brunswick', 'NB'],
      ['Manitoba', 'MB'],
      ['British Columbia', 'BC'],
      ['Prince Edward Island', 'PE'],
      ['Saskatchewan', 'SK'],
      ['Alberta', 'AB'],
      ['Newfoundland and Labrador', 'NL']
    ]
  end

  def mexican_states
    [
      ['Aguascalientes', 'MX - AG'],
      ['Baja California', 'MX - BN'],
      ['Baja California Sur', 'MX - BS'],
      ['Campeche', 'MX - CM'],
      ['Chiapas', 'MX - CP'],
      ['Chihauhua', 'MX - CH'],
      ['Coahuila', 'MX - CA'],
      ['Colima', 'MX - CL'],
      ['Federal District', 'MX - DF'],
      ['Durango', 'MX - DU'],
      ['Guanajuato', 'MX - GT'],
      ['Guerrero', 'MX - GR'],
      ['Hidalgo', 'MX - HI'],
      ['Jalisco', 'MX - JA'],
      ['México', 'MX - MX'],
      ['Michoacán', 'MX - MC'],
      ['Morelos', 'MX - MR'],
      ['Nayarit', 'MX - NA'],
      ['Nuevo León', 'MX - NL'],
      ['Oaxaca', 'MX - OA'],
      ['Puebla', 'MX - PU'],
      ['Querétaro', 'MX - QE'],
      ['Quintana Roo', 'MX - QR'],
      ['San Luis Potosí', 'MX - SL'],
      ['Sinaloa', 'MX - SI'],
      ['Sonora', 'MX - SO'],
      ['Tabasco', 'MX - TB'],
      ['Tamaulipas', 'MX - TM'],
      ['Tlaxcala', 'MX - TL'],
      ['Veracruz', 'MX - VE'],
      ['Yucatán', 'MX - YU'],
      ['Zacatecas', 'MX - ZA']
    ]
  end
end
