#!/bin/sh

set -e
set -x

USAGE="$0: appname"
if [ $# -lt 1 ]; then
  echo "Error: appname is required.\n$USAGE" >&2
  exit 1
fi

# http://stackoverflow.com/a/677212/358804
if ! hash cf-blue-green 2>/dev/null; then
  npm install -g cf-blue-green
fi

cf-blue-green $1 -f web-manifest.yml
cf-blue-green ${1}-worker -f worker-manifest.yml
